name: Delete Artifacts

on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: List Artifacts
      id: list_artifacts
      run: |
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
        | jq '.artifacts[] | {id: .id, name: .name}'

    - name: Delete Artifacts
      run: |
        for artifact_id in $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
        | jq -r '.artifacts[] | .id'); do
          curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id";
        done
